de:
  languageName: Deutsch
  weight: 1
  title: Allegra March
  contentDir: content/de
  params:
    description: Eine Plattform zur Förderung von Integration durch Clubs in der Schweiz.
  menu:
    main:
      - name: Über uns
        url: about
        weight: 1
      - name: Team
        url: people
        weight: 2
      - name: Atelier
        url: atelier
        weight: 3
      - name: Mitteilungen
        url: notices
        weight: 4
        identifier: notices
      - name: Agenda
        url: /notices/agenda/
        weight: 4.1
        parent: notices
      - name: Info-Point
        url: /notices/infopoint/
        weight: 4.2
        parent: notices
      - name: Gallery
        url: /notices/gallery/
        weight: 4.3
        parent: notices
      - name: News
        url: /notices/info/
        weight: 4.4
        parent: notices
      - name: Kontakt
        url: contact
        weight: 5
      - name: Datenschutz
        url: privacy
        weight: 7

en:
  languageName: English
  weight: 2
  title: Allegra March
  contentDir: content/en
  params:
    description: A platform that supports integration in Switzerland through social clubs.
  menu:
    main:
      - name: About
        url: about
        weight: 1
      - name: Team
        url: people
        weight: 2
      - name: Clubs
        url: atelier
        weight: 3
      - name: News
        url: news
        weight: 4
        identifier: news
      - name: Agenda
        url: /category/event/
        weight: 4.1
        parent: news
      - name: Info-Point
        url: /category/infopoint/
        weight: 4.2
        parent: news
      - name: Gallery
        url: /category/gallery/
        weight: 4.3
        parent: news
      - name: News
        url: /category/info/
        weight: 4.4
        parent: news
      - name: Contact
        url: contact
        weight: 5
      - name: Privacy
        url: privacy
        weight: 6

uk:
  languageName: Українська
  weight: 3
  title: Allegra March
  contentDir: content/uk
  params:
    description: Платформа для підтримки інтеграції в Швейцарії через клуби за інтересами.
  menu:
    main:
      - name: Про нас
        url: about
        weight: 1
      - name: Команда
        url: people
        weight: 2
      - name: Клуби
        url: atelier
        weight: 3
      - name: Новини
        url: news
        weight: 4
        identifier: news
      - name: Події
        url: /category/event/
        weight: 4.1
        parent: news
      - name: Info-Point
        url: /category/infopoint/
        weight: 4.2
        parent: news
      - name: Галерея
        url: /category/gallery/
        weight: 4.3
        parent: news
      - name: Новини
        url: /category/info/
        weight: 4.4
        parent: news
      - name: Контакт
        url: contact
        weight: 5
      - name: Приватність
        url: pryvatnist
        weight: 6

# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
#en:
  #languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
#zh:
#  languageCode: zh-Hans
#  contentDir: content/zh
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
