de:
  languageName: Deutsch
  weight: 1
  title: Allegra March
  contentDir: content/de
  params:
    description: Eine Plattform zur Förderung von Integration durch Clubs in der Schweiz.
  menu:
    main:
      - name: Verein
        weight: 1
        identifier: about
      - name: Über uns
        url: /about/about/
        weight: 1.1
        parent: about
      - name: Team
        url: /about/team/
        weight: 1.2
        parent: about
      - name: Dank
        pageRef: /about/dank/
        weight: 1.3
        parent: about
      - name: Atelier
        url: atelier
        weight: 3
      - name: Mitteilungen
        url: notices
        weight: 4
        identifier: notices
      - name: Agenda
        url: /notices/agenda/
        weight: 4.1
        parent: notices
      - name: Info-Point
        url: /notices/infopoint/
        weight: 4.2
        parent: notices
      - name: Gallery
        url: /notices/gallery/
        weight: 4.3
        parent: notices
      - name: News
        url: /notices/info/
        weight: 4.4
        parent: notices
      - name: Kontakt
        url: contact
        weight: 5
      - name: Datenschutz
        url: privacy
        weight: 7

en:
  languageName: English
  weight: 2
  title: Allegra March
  contentDir: content/en
  params:
    description: A platform that supports integration in Switzerland through social clubs.
  menu:
    main:
      - name: Association
        weight: 1
        identifier: about
      - name: About us
        url: /about/about/
        weight: 1.1
        parent: about
      - name: Team
        url: /about/team/
        weight: 1.2
        parent: about
      - name: Gratitude
        pageRef: /about/dank/
        weight: 1.3
        parent: about

      - name: Ateliers
        url: atelier
        weight: 3

      - name: Notices
        url: notices
        weight: 4
        identifier: notices
      - name: Agenda
        url: /notices/agenda/
        weight: 4.1
        parent: notices
      - name: Info-Point
        url: /notices/infopoint/
        weight: 4.2
        parent: notices
      - name: Gallery
        url: /notices/gallery/
        weight: 4.3
        parent: notices
      - name: News
        url: /notices/info/
        weight: 4.4
        parent: notices

      - name: Contact
        url: contact
        weight: 5

      - name: Privacy Policy
        url: privacy
        weight: 7

uk:
  languageName: Українська
  weight: 3
  title: Allegra March
  contentDir: content/uk
  params:
    description: Платформа для підтримки інтеграції в Швейцарії через клуби за інтересами.
  menu:
    main:
      - name: Організація
        weight: 1
        identifier: about
      - name: Про нас
        url: /about/about/
        weight: 1.1
        parent: about
      - name: Команда
        url: /about/team/
        weight: 1.2
        parent: about
      - name: Подяка
        pageRef: /about/dank/
        weight: 1.3
        parent: about

      - name: Ательє
        url: atelier
        weight: 3

      - name: Повідомлення
        url: notices
        weight: 4
        identifier: notices
      - name: Порядок денний
        url: /notices/agenda/
        weight: 4.1
        parent: notices
      - name: Інфо-Пойнт
        url: /notices/infopoint/
        weight: 4.2
        parent: notices
      - name: Галерея
        url: /notices/gallery/
        weight: 4.3
        parent: notices
      - name: Новини
        url: /notices/info/
        weight: 4.4
        parent: notices

      - name: Контакт
        url: contact
        weight: 5

      - name: Політика конфіденційності
        url: privacy
        weight: 7

